### ISSUE TITLE
Canonical URL Issues in Glossary Application

### ISSUE THREAD

**Issue by welshja** [NCIOCPL/glossary-app#203]
### Issue description
We noticed a large decrease in rankings and traffic to the dictionaries migrated to using the glossary application. Based on errors we are seeing in Google Webmaster tools, we believe it has to do with the way  the canonical URL is being set either being inconsistent or incorrect. This is causing crawl errors in Google and resulting in these pages not being indexed/ranked accordingly.

Links to reports pointing to issues in Google Webmaster tools:
https://search.google.com/u/1/search-console/index/drilldown?resource_id=https%3A%2F%2Fwww.cancer.gov%2F&item_key=CAMYGCAC

https://search.google.com/search-console/index/drilldown?resource_id=https%3A%2F%2Fwww.cancer.gov%2F&item_key=CAMYGSAC

Please investigate.

> **ESTIMATE** 20

### Steps to reproduce the issue

1.  
2. 
3. 

### What's the expected result?
-

### What's the actual result?
-

### Additional details / screenshot
- ![Screenshot]()

### Related Tickets
* Issue #9999
* Issue #9999

**Comment by bryanpizzillo** [comment]
Some threads
https://support.google.com/webmasters/thread/26525289?hl=en
https://support.google.com/webmasters/thread/20331557?hl=en

**Comment by bryanpizzillo** [comment]
In a Google hangout it was indicated that there should be no canonical, hreflang or robots in the static HTML generated by the server and that Google should be able to understand what JS is adding. Otherwise there is a conflict between the static HTML metatags and the Javascript ones. I do not know if this affects things like title, or just crawler metadata. 

https://www.seroundtable.com/google-process-canonicals-in-javascript-26293.html

**Comment by amydugan** [comment]
Closed with release v1.1.27 8/18/20
